# This is a configuration file `nvidia-container-runtime-hook`
# Required to disable cgroups for Docker rootless as of Docker 19.03.
# via https://kien.ai/docker-rootless

disble-require = false

[nvidia-container-cli]
#root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
#debug = "/var/log/nvidia-container-runtime-hook.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
no-cgroups = true
#user = "root:video"
ldconfig = "@/sbin/ldconfig.real"

