name: Build Docker images

on:
    workflow_dispatch:
    schedule:
        # Every night at 03:00 UTC
        - cron: "0 3 * * *"
    push:
      branches:
        - master

jobs:
    check-prerequisites:
        runs-on: ${{ matrix.platform }}
        strategy:
            fail-fast: false
            matrix:
                platform: ["intel", "nvidia"]
        steps:
            - uses: actions/checkout@v2
              with:
                  lfs: true
            - name: Check whether system is setup correctly for building and running Celerity CI containers
              run: bash ./check-prerequisites.sh

    build-sycl:
        needs: [check-prerequisites]
        runs-on: ${{ matrix.platform }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - sycl-version: "computecpp:2.6.0"
                      platform: "intel"
                    - sycl-version: "computecpp:2.8.0"
                      platform: "intel"
                    - sycl-version: "dpcpp:HEAD"
                      platform: "intel"
                    - sycl-version: "dpcpp:7735139b"
                      platform: "intel"
                    - sycl-version: "hipsycl:HEAD"
                      platform: "nvidia"
                    - sycl-version: "hipsycl:7b00e2ef"
                      platform: "nvidia"
                    - sycl-version: "hipsycl:v0.9.1"
                      platform: "nvidia"
        steps:
            - uses: actions/checkout@v2
              with:
                  lfs: true
            - name: Build Docker container for ${{ matrix.sycl-version }}
              run: bash ./build.sh ${{ matrix.sycl-version }}
              if: ${{ github.event_name == 'schedule' }}
            - name: Force-build Docker container for ${{ matrix.sycl-version }}
              run: bash ./build.sh -f ${{ matrix.sycl-version }}
              if: ${{ github.event_name != 'schedule' }}

    build-lint:
        needs: [check-prerequisites]
        runs-on: ${{ matrix.platform }}
        strategy:
            fail-fast: false
            matrix:
                # HACK: We need to ensure the lint container image exists on all runners
                platform: ["intel", "nvidia"]
        steps:
            - uses: actions/checkout@v2
            - name: Build Celerity linting container
              run: bash ./build-lint.sh
