name: Nightly Build

on:
  schedule:
    # TODO: Do once per night
    - cron: "30 * * * *"

jobs:
  build-sycl:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: ["intel", "nvidia"] # This selects the runner that builds the image
        implementation: ["dpc++", "hipsycl"]
        version: ["HEAD"]
        include:
          - implementation: "dpc++"
            version: "sycl-nightly/20210803"
          - implementation: "hipsycl"
            version: "v0.9.1"
        exclude:
          - platform: "intel"
            implementation: "hipsycl"
          - platform: "nvidia"
            implementation: "computecpp"
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker container for SYCL implementation
        run: bash ./docker/build-image.sh ${{ matrix.implementation }} ${{ matrix.version }}
